export const featureChoices = [
  { title: "React (via Vite)", value: "react", selected: true, description: "Modern React setup" },
  { title: "TypeScript", value: "typescript", selected: true, description: "Type safety" },
  { title: "Electron", value: "electron", selected: true, description: "Desktop shell" },
  { title: "Preload (secure IPC)", value: "preload", selected: true, description: "Expose safe APIs" },
  { title: "ESLint", value: "eslint", selected: true, description: "Linting rules" },
  { title: "Prettier", value: "prettier", selected: true, description: "Code formatter" },
  { title: "Git Init", value: "git", selected: true, description: "Initialize repository" },
  { title: "SQLite Support", value: "sqlite", description: "Local database" },
  { title: "Zod or Joi Validation", value: "validation", description: "Schema validation" },
  { title: "Dotenv Support", value: "dotenv", description: "Environment variables" },
  { title: "Git Hooks (Husky)", value: "husky", description: "Pre-commit hooks" },
  { title: "Auto-generated README.md", value: "readme", description: "Create README file" },
  { title: "AD/SSO Login Stub", value: "sso", description: "Placeholder auth" },
  { title: "Roadmap.md + Agents.md", value: "agents", description: "Planning docs" },
  { title: "Dark Mode Support", value: "darkmode", selected: true, description: "OS theme detection" },
  { title: "Transparent Custom Window Bar", value: "frameless", description: "Borderless window" },
  { title: "Global App Config File", value: "metaConfig", description: "config.json stub" },
  { title: "Auto-Updater Stub", value: "autoupdate", description: "Update placeholder" }
];
